[versions]
agp = "8.5.0"
binaryCompatibilityValidator = "0.14.0"
detekt = "1.23.6"
diffUtils = "4.12"
junit = "5.10.2"
kotlin = "1.9.24"
ktfmt-plugin = "0.18.0"
ktfmt = "0.50"
pluginPublish = "1.2.1"
truth = "1.4.2"
versionCheck = "0.51.0"

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt-plugin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck" }

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
jupiter = { module = "org.junit.jupiter:junit-jupiter" }
jupiter-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
diffUtils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "diffUtils" }
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
