[versions]
agp = "8.13.1"
binaryCompatibilityValidator = "0.18.1"
detekt = "1.23.8"
diffUtils = "4.16"
junit = "6.0.0"
kotlin = "2.2.20"
ktfmt-plugin = "0.23.0"
ktfmt = "0.59"
pluginPublish = "2.0.0"
truth = "1.4.5"

[plugins]
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binaryCompatibilityValidator" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktfmt = { id = "com.ncorti.ktfmt.gradle", version.ref = "ktfmt-plugin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
jupiter = { module = "org.junit.jupiter:junit-jupiter" }
jupiter-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
diffUtils = { module = "io.github.java-diff-utils:java-diff-utils", version.ref = "diffUtils" }
ktfmt = { module = "com.facebook:ktfmt", version.ref = "ktfmt" }
